### ISSUE TITLE
Make parts of the color scheme configurable

### ISSUE THREAD

**Issue by hplahar** [TeselaGen/openVectorEditor#380]
e.g. the yellow ring for plasmid view is now white

@tnrich

**Comment by tnrich** [comment]
@hplahar you should be able to change that one quite easily already actually just via css: 
```css
.veAxisFill {
 fill: yellow!important;
}
```
try that?
